---
title       : R Tutorial
subtitle    : March
author      : Jose Padarian and Sebastian Campbell
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : quiz            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## Read-And-Delete

1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

--- .class #id 

## Slide 2

```{r}
plot(10:1, 1:10)
```

---&radio .quiz

## Markdown quiz
In order to determine if smoking causes cancer, researchers surveyed a large sample of adults.  For each adult, they recorded whether the person had smoked regularly at any period in their life and whether the person had cancer.  They then compared the proportion of cancer cases in those who had smoked regularly at some time in their life with the proportion of cases in those who had never smoked regularly at any point in their life.  The researchers found a higher proportion of cancer cases among those who had smoked regularly than among those who had never smoked regularly. This is:

1. _an observational study._
2. a double blind experiment.
3. a block design.
4. an experiment, but not a double blind experiment.

*** explanation

It is an *observational study* since the researchers did not control the explanatory variable: smoker.
